export default {
  // news
  GET_NEWS_BY_TAG: 'GET_NEWS_BY_TAG',
  CREATE_NEWS: 'CREATE_NEWS',
  UPDATE_NEWS: 'UPDATE_NEWS',
  DEL_NEWS: 'DEL_NEWS',
  UPDATE_NEWS_STATUS: 'UPDATE_NEWS_STATUS',

  // videos
  GET_VIDEOS_BY_TYPE: 'GET_VIDEOS_BY_TYPE',
  DEL_VIDEO: 'DEL_VIDEO',
  CREATE_VIDEO: 'CREATE_VIDEO',
  UPDATE_VIDEO: 'UPDATE_VIDEO',
  UPDATE_VIDEO_STATUS: 'UPDATE_VIDEO_STATUS',

  // user
  GET_PROFILE: 'GET_PROFILE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // menu
  GET_ALL_MENU: 'GET_ALL_MENU',
  UPDATE_NAVPATH: 'UPDATE_NAVPATH',

  // ERROR MESSAGE
  ERROR_SERVER:'服务器繁忙，请稍候再试'
}
